name: Build ejejmplo on macOS

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Set up Maven 3.8.8
        run: |
          curl -O https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz 
          tar -xzf apache-maven-3.8.8-bin.tar.gz
          echo "$(pwd)/apache-maven-3.8.8/bin" >> $GITHUB_PATH
      - name: Download GraalVM CE for Java 17
        run: |
          echo "Downloading GraalVM CE for Java 17..."
          curl -L -o graalvm.tar.gz "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-darwin-amd64-22.3.1.tar.gz"
          tar -xzf graalvm.tar.gz
          echo "GRAALVM_HOME=$(pwd)/graalvm-ce-java17-22.3.1/Contents/Home" >> $GITHUB_ENV
      - name: Build with Maven (GluonFX)
        run: |
          echo "Using GraalVM at: $GITHUB_WORKSPACE/graalvm-ce-java17-22.3.1/Contents/Home"
          mvn clean gluonfx:build gluonfx:package -DgraalvmHome="$GITHUB_WORKSPACE/graalvm-ce-java17-22.3.1/Contents/Home" -DskipSigning=true
          

      - name: List generated files
        run: |
          echo "Listando archivos en el directorio actual..."
          find . -type f

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: ejejmplo-dmg
          path: target/gluonfx/x86_64-darwin/ejejmplo-1.0.0.dmg

